version: 0.1

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - python3 -m venv ~/.flask_env
      - source ~/.flask_env/bin/activate
      - make install

  build:
    commands:
      - make deploy
